# Generated by Django 4.2.6 on 2023-11-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0004_alter_student_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                related_name="students_list", to="university.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_list",
                to="university.group",
            ),
        ),
    ]
