# Generated by Django 4.2.6 on 2023-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0005_group_students_alter_student_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="group",
        ),
        migrations.AddField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(related_name="groups", to="university.group"),
        ),
    ]
