# Generated by Django 4.2.6 on 2023-11-19 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0006_remove_student_group_student_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="students",
        ),
    ]
