# Generated by Django 4.2.6 on 2023-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0008_alter_student_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Phone number"
            ),
        ),
    ]
